# Generated by Django 3.1.1 on 2020-10-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangonautic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('title_description', models.TextField(blank=True, null=True)),
                ('title_btn', models.CharField(blank=True, default='Join', max_length=50, null=True)),
                ('title_btn_url', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
