# Generated by Django 3.1.1 on 2020-10-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangonautic', '0002_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail_image_url',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
