# Generated by Django 3.1.1 on 2020-10-26 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangonautic', '0003_auto_20201022_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='VariationValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('variation_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='djangonautic.variation')),
            ],
        ),
        migrations.CreateModel(
            name='VariationCombination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_name', models.ManyToManyField(default=None, to='djangonautic.Variation')),
                ('variation_value', models.ManyToManyField(default=None, to='djangonautic.VariationValue')),
            ],
        ),
        migrations.AddField(
            model_name='variation',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='djangonautic.product'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageURL', models.URLField(max_length=1000)),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='djangonautic.product')),
            ],
        ),
    ]
