# Generated by Django 3.1.1 on 2020-10-29 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangonautic', '0004_auto_20201026_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variationcombination',
            name='variation_value',
        ),
        migrations.AddField(
            model_name='variationcombination',
            name='variation_value',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='djangonautic.variationvalue'),
        ),
    ]
