# Generated by Django 3.1.1 on 2020-10-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangonautic', '0005_auto_20201029_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='variationcombination',
            name='sku',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
