# Generated by Django 3.1.1 on 2020-10-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangonautic', '0006_variationcombination_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variationcombination',
            name='variation_value',
        ),
        migrations.AddField(
            model_name='variationcombination',
            name='variation_value',
            field=models.ManyToManyField(default=None, to='djangonautic.VariationValue'),
        ),
    ]
