# Generated by Django 3.1.1 on 2020-11-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangonautic', '0009_auto_20201101_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variationcombination',
            name='price',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
