# Generated by Django 3.1.1 on 2020-11-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangonautic', '0010_auto_20201101_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variationcombination',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
