# Generated by Django 3.1.1 on 2020-11-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangonautic', '0011_auto_20201101_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variationcombination',
            name='price',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
