# Generated by Django 3.1.1 on 2020-11-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangonautic', '0012_auto_20201101_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='imageURL',
            field=models.URLField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='variationvalue',
            name='value',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
