# Generated by Django 3.1.1 on 2020-11-01 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangonautic', '0013_auto_20201101_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variationcombination',
            old_name='price',
            new_name='var_price',
        ),
    ]
