# Generated by Django 3.1.1 on 2020-11-01 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangonautic', '0014_auto_20201101_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variationcombination',
            name='var_price',
        ),
    ]
