# Generated by Django 3.1.1 on 2020-11-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangonautic', '0015_remove_variationcombination_var_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='variationcombination',
            name='price',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
