# Generated by Django 3.1.1 on 2020-11-01 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangonautic', '0016_variationcombination_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variationcombination',
            name='price',
        ),
    ]
