# Generated by Django 3.1.1 on 2020-11-01 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangonautic', '0017_remove_variationcombination_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariationCombination',
        ),
    ]
