# Generated by Django 3.1.1 on 2020-11-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangonautic', '0018_delete_variationcombination'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariationCombination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(default=None, max_length=100)),
                ('variation_name', models.ManyToManyField(default=None, to='djangonautic.Variation')),
                ('variation_value', models.ManyToManyField(default=None, to='djangonautic.VariationValue')),
            ],
        ),
    ]
