# Generated by Django 3.1.1 on 2020-11-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangonautic', '0019_variationcombination'),
    ]

    operations = [
        migrations.AddField(
            model_name='variationcombination',
            name='price',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
