# Generated by Django 3.1.1 on 2020-11-14 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangonautic', '0020_variationcombination_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='variationcombination',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='djangonautic.product'),
        ),
        migrations.AddField(
            model_name='variationvalue',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='djangonautic.product'),
        ),
        migrations.CreateModel(
            name='VariationPictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageURL', models.URLField(max_length=1000, null=True)),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='djangonautic.product')),
                ('value', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='djangonautic.variationvalue')),
                ('variation_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='djangonautic.variation')),
            ],
        ),
    ]
