# Generated by Django 3.1.1 on 2020-11-14 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangonautic', '0021_auto_20201114_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variationcombination',
            name='product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangonautic.product'),
        ),
        migrations.AlterField(
            model_name='variationpictures',
            name='product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangonautic.product'),
        ),
    ]
