# Generated by Django 3.1.1 on 2020-11-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangonautic', '0022_auto_20201114_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productURL',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
