# Generated by Django 3.1.1 on 2020-11-14 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangonautic', '0024_auto_20201114_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='variationcombination',
            name='variation_name',
            field=models.ManyToManyField(default=None, null=True, to='djangonautic.Variation'),
        ),
        migrations.AlterField(
            model_name='variationcombination',
            name='variation_value',
            field=models.ManyToManyField(default=None, null=True, to='djangonautic.VariationValue'),
        ),
        migrations.AlterField(
            model_name='variationpictures',
            name='value',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangonautic.variationvalue'),
        ),
        migrations.AlterField(
            model_name='variationpictures',
            name='variation_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangonautic.variation'),
        ),
        migrations.AlterField(
            model_name='variationvalue',
            name='variation_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangonautic.variation'),
        ),
    ]
