# Generated by Django 3.1.1 on 2020-11-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangonautic', '0025_auto_20201114_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variationcombination',
            name='variation_name',
            field=models.ManyToManyField(default=None, to='djangonautic.Variation'),
        ),
        migrations.AlterField(
            model_name='variationcombination',
            name='variation_value',
            field=models.ManyToManyField(default=None, to='djangonautic.VariationValue'),
        ),
    ]
