# Generated by Django 3.1.1 on 2020-11-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangonautic', '0026_auto_20201114_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default=None, max_length=1000, null=True)),
            ],
        ),
    ]
